### ISSUE TITLE
Output Targets Tentative Roadmap

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/stencil-ds-output-targets#242]
The output targets repository is now co-managed by both the Stencil Core team as well as the Framework Core team at Ionic. These teams will be responsible for the ongoing development and maintenance of this project.

# Q1
- [x] Evaluate and decide on team ownership of repository.
- [x] Set-up Ionitron for issue triaging and labeling of the repository.
- [x] Set-up codeowners for review process.
- [ ] Triage open issues and apply labels to classify the current state of them.

# Q2
- [ ] #219
- [x] #207
- [ ] #122

# Q3

- [x]  #143
- [ ] #255

# Q4

N/A
